#ifndef MDEFINES_H
#define MDEFINES_H

#include <HardwareSerial.h>

#define MODBUS_BYTE 8
#define MODBUS_CRC_BYTE_COUNT 2
#define MODBUS_MAX_FRAME_SIZE SERIAL_RX_BUFFER_SIZE

#define MODBUS_ID_BROADCAST 0
#define MODBUS_ID_MIN 1
#define MODBUS_ID_MAX 247

//byte position in request frame
#define MODBUS_ID 0
#define MODBUS_FUNCTION 1
#define MODBUS_ADDR_HIGH 2
#define MODBUS_ADDR_LOW 3
#define MODBUS_QUANTITY_HIGH 4
#define MODBUS_QUANTITY_LOW 5
#define MODBUS_VALUE_HIGH 4
#define MODBUS_VALUE_LOW 5
#define MODBUS_BYTE_COUNT 6

//function codes
#define MODBUS_READ_OUTPUTS 1
#define MODBUS_READ_INPUTS 2
#define MODBUS_READ_OUTPUT_REGISTERS 3
#define MODBUS_READ_INPUT_REGISTERS 4
#define MODBUS_WRITE_OUTPUT 5
#define MODBUS_WRITE_REGISTER 6
#define MODBUS_WRITE_N_OUTPUTS 0x0F
#define MODBUS_WRITE_N_REGISTERS 0x10

#define MODBUS_ERR_OFFSET 0x80

//error codes
#define MODBUS_ERR_ILLEGAL_FUNCTION 1
#define MODBUS_ERR_ILLEGAL_ADDR 2
#define MODBUS_ERR_ILLEGAL_DATA 3
#define MODBUS_ERR_SLAVE_FAILURE 4

#endif