#define MODBUS_BYTE 8

#define MODBUS_ID_BROADCAST 0

#define MODBUS_CRC 0x4B37
#define MODBUS_CRC_BYTE_COUNT 2

#ifndef MODBUS_FRAME_LENGTH 
#define MODBUS_FRAME_LENGTH 64
#endif

//byte position in request frame
#define MODBUS_ID 0
#define MODBUS_FUNCTION 1
#define MODBUS_ADDR_HIGH 2
#define MODBUS_ADDR_LOW 3
#define MODBUS_QUANTITY_HIGH 4
#define MODBUS_QUANTITY_LOW 5
#define MODBUS_VALUE_HIGH 4
#define MODBUS_VALUE_LOW 5
#define MODBUS_BYTE_COUNT 6

//function codes
#define MODBUS_READ_OUTPUTS 1
#define MODBUS_READ_INPUTS 2
#define MODBUS_READ_OUTPUT_REGISTERS 3
#define MODBUS_READ_INPUT_REGISTERS 4
#define MODBUS_WRITE_OUTPUT 5
#define MODBUS_WRITE_REGISTER 6
#define MODBUS_WRITE_N_OUTPUTS 0x0F
#define MODBUS_WRITE_N_REGISTERS 0x10

//storage defines
#ifndef MODBUS_AQ_LENGTH
#error missing MODBUS_AQ_LENGTH
#endif

#ifndef MODBUS_DQ_LENGTH
#error missing MODBUS_DQ_LENGTH
#endif

#ifndef MODBUS_AI_LENGTH
#error missing MODBUS_AI_LENGTH
#endif

#ifndef MODBUS_DI_LENGTH
#error missing MODBUS_DI_LENGTH
#endif

#define MODBUS_AQ_FIRST_ADDR 0
#define MODBUS_DQ_FIRST_ADDR 0
#define MODBUS_AI_FIRST_ADDR 0
#define MODBUS_DI_FIRST_ADDR 0

#define MODBUS_AQ_LAST_ADDR MODBUS_AQ_LENGTH-1
#define MODBUS_DQ_LAST_ADDR MODBUS_DQ_LENGTH-1
#define MODBUS_AI_LAST_ADDR MODBUS_AI_LENGTH-1
#define MODBUS_DI_LAST_ADDR MODBUS_DI_LENGTH-1

#define MODBUS_ERR_OFFSET 0x80

//error codes
#define MODBUS_ERR_ILLEGAL_FUNCTION 1
#define MODBUS_ERR_ILLEGAL_ADDR 2
#define MODBUS_ERR_ILLEGAL_DATA 3
#define MODBUS_ERR_SLAVE_FAILURE 4